export default [
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 2.5,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-14',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'KONDITORI SWEDISH',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Square',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'xn9LmZKDDxi33yP8KO4ytbZk3R6jn0FL6K4jR',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 32,
        category: [
            'Travel',
            'Public Transportation Services',
        ],
        category_id: '22014000',
        date: '2018-02-14',
        location: {
            address: '347 Madison Ave',
            city: 'New York',
            lat: 40.754395,
            lon: -73.97773,
            state: 'NY',
            store_number: null,
            zip: '10017',
        },
        name: 'Metropolitan Transportation Authority',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'a3baDQ566zfkkLgVzxyLtgLarV0enxhPD1gaP',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 14,
        category: [
            'Travel',
            'Charter Buses',
        ],
        category_id: '22007000',
        date: '2018-02-14',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'MA',
            store_number: null,
            zip: null,
        },
        name: 'PETER PAN BUS WEBSITE 04137812900',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'JKOQyZXMMzFJJVADXvQktLY1eE3Ry0Fg1Rypx',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 84.38,
        category: [
            'Food and Drink',
            'Restaurants',
        ],
        category_id: '13005000',
        date: '2018-02-14',
        location: {
            address: '314 W 11th St',
            city: 'New York',
            lat: 40.735615,
            lon: -74.006668,
            state: 'NY',
            store_number: null,
            zip: '10014',
        },
        name: 'The Spotted Pig',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'n8DMXqw00yTEEdZkxDmVTpKDZE0oQEI8E9xxE',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 30.85,
        category: [
            'Shops',
            'Supermarkets and Groceries',
        ],
        category_id: '19047000',
        date: '2018-02-14',
        location: {
            address: '214 3rd St',
            city: 'Brooklyn',
            lat: 40.6755282563532,
            lon: -73.98875713348389,
            state: 'NY',
            store_number: '10',
            zip: '11215',
        },
        name: 'Whole Foods',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'Q4QLBroggzupp7kKXaerF1xd5YzvXYfk7rKKQ',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 13.23,
        category: [
            'Service',
            'Food and Beverage',
        ],
        category_id: '18021000',
        date: '2018-02-13',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'MA',
            store_number: null,
            zip: null,
        },
        name: '*SWEETGREEN6103',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'XdMyrk5ggziLLOgemPxOfgKkgRjnwET7Vagan',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 24.95,
        category: null,
        category_id: null,
        date: '2018-02-13',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'CCBill.com *Planta Ro +8885969279 ESP',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'a3baDQ566zfkkLgVzxyXigbJyVpnDxFPQM6eb',
        transaction_type: 'digital',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 10.83,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-13',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'JUICE GENERATION 102 P',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'qnwQo9D44Ai665y0zoBRCoYgO89R8xCajEVRQ',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 18.51,
        category: [
            'Service',
        ],
        category_id: '18000000',
        date: '2018-02-13',
        location: {
            address: '138 5th Ave',
            city: 'New York',
            lat: 40.739082,
            lon: -73.99192,
            state: 'NY',
            store_number: null,
            zip: '10011',
        },
        name: 'Mcnally Gregory A',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'qnwQo9D44Ai665y0zoBRCxDVjgL5zaIaY8K8j',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 4,
        category: [
            'Food and Drink',
            'Restaurants',
            'Coffee Shop',
        ],
        category_id: '13005043',
        date: '2018-02-13',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQU*SQ *GIMME| COFFEE',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'PrZ63qoggzSgg7jyDv1XcaJYpvVeqxUMxpzpz',
        transaction_id: '8Y1rJzVLLpfVVMbxEzn1swnEgMdRzmF5wnD9z',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 24.95,
        category: null,
        category_id: null,
        date: '2018-02-13',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'SegpayEU.com*GDV 8664504000 ESP',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'xn9LmZKDDxi33yP8KO4LiboYdRDn80ILE8dvQ',
        transaction_type: 'digital',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 20.9,
        category: [
            'Service',
            'Personal Care',
        ],
        category_id: '18045000',
        date: '2018-02-13',
        location: {
            address: '387  Avenue Of The Americas   Frnt 1',
            city: 'New York',
            lat: 40.733204,
            lon: -74.000229,
            state: 'NY',
            store_number: null,
            zip: '10014',
        },
        name: 'Vada Spa',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: '3YOk0zVaapfww0aZ7renu99d3oZkeDTevQ1Q1',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 5.75,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-12',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQ *KONDITORI SWED',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Square',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'JKOQyZXMMzFJJVADXvQ4CpJQX9woZVUgLkrkp',
        transaction_id: 'N0Qd7Zommzs88R9Bo36RH9Bb9MEa71IKXLDLD',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 4.5,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-11',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQ *KONDITORI SWED',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Square',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: '0YE3QNejjpfDDEOx31eMHxPoREK1vzUM7JPAA',
        transaction_id: '3YOk0zVaapfww0aZ7re6HaaDwkA0LbievQ39O',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 4.5,
        category: [
            'Food and Drink',
            'Restaurants',
            'Coffee Shop',
        ],
        category_id: '13005043',
        date: '2018-02-11',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQU*SQ *GOTAN WILLIAMS',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'xn9LmZKDDxi33yP8KO4aC5eKZv4zX0IL6ozgX',
        transaction_id: 'qnwQo9D44Ai665y0zoBDuooJezEMgphajPmbP',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 18.77,
        category: [
            'Food and Drink',
            'Restaurants',
            'Coffee Shop',
        ],
        category_id: '13005043',
        date: '2018-02-11',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQU*SQ *GOTAN WILLIAMS',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'a3baDQ566zfkkLgVzxynC6z9LMOPoxUPD4XVM',
        transaction_id: 'yn7DRVk11JiyyK8ZQdgXtRROnKzMbXFLz9e47',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 4.36,
        category: [
            'Shops',
            'Pharmacies',
        ],
        category_id: '19043000',
        date: '2018-02-10',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Duane Reade',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: '4YEANgVxxpfDDzXZMxBespnmdnp4QYC0LEQLj',
        transaction_id: 'PrZ63qoggzSgg7jyDv1YIbbA9qkdv5UMyD0ZJ',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 0.31,
        category: [
            'Shops',
            'Supermarkets and Groceries',
        ],
        category_id: '19047000',
        date: '2018-02-10',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Whole Foods',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'a3baDQ566zfkkLgVzxyDua4K63qAxRCPDaaEx',
        transaction_id: '1Yzy7xErrpfRRZwNvJ4dIwwX1ZKdABh1VEzXq',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 9.2,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-09',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'JUICE GENERATION 102 P',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'MvAXPjEggziRR7bNKE0ZH5YoZJL1oXIQNkxwv',
        transaction_id: 'D1Q9ODo00zCXXPE3mrjNcnnRzJNPjrFoN0x8z',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 18.33,
        category: null,
        category_id: null,
        date: '2018-02-09',
        location: {
            address: null,
            city: 'New York City',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'ROOFTOP/MOXY HOTEL TS',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'Oj0wB7oEEzTDDoq3VzxOU8jAMDJyAaCMANr9L',
        transaction_id: 'BmNg30pAAzfEE7oDVON3t667VL93mXFxDQPAL',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 9.09,
        category: [
            'Food and Drink',
            'Restaurants',
        ],
        category_id: '13005000',
        date: '2018-02-08',
        location: {
            address: '62  Prince St',
            city: 'New York',
            lat: 40.723644,
            lon: -73.996803,
            state: 'NY',
            store_number: null,
            zip: '10012',
        },
        name: 'Soho Park',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: '0YE3QNejjpfDDEOx31eeSB0g5zxnzntM7xQJY',
        transaction_id: 'Z6vkyr5ggzh11a5xngNXCg6YQdEEvpfQZ9D4P',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 32,
        category: [
            'Travel',
            'Public Transportation Services',
        ],
        category_id: '22014000',
        date: '2018-02-07',
        location: {
            address: '347 Madison Ave',
            city: 'New York',
            lat: 40.754395,
            lon: -73.97773,
            state: 'NY',
            store_number: null,
            zip: '10017',
        },
        name: 'Metropolitan Transportation Authority',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'qnwQo9D44Ai665y0zozvfEZxaxnkALCaXN6Jy',
        transaction_id: '8Y1rJzVLLpfVVMbxEznJtabeprggQ3C56K31Q',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 14,
        category: [
            'Travel',
            'Charter Buses',
        ],
        category_id: '22007000',
        date: '2018-02-07',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'MA',
            store_number: null,
            zip: null,
        },
        name: 'PETER PAN BUS WEBSITE 04137812900',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '4YEANgVxxpfDDzXZMxBMFYBNrBjgqBC0LJd8o',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 13.01,
        category: [
            'Food and Drink',
            'Restaurants',
            'Thai',
        ],
        category_id: '13005004',
        date: '2018-02-07',
        location: {
            address: '212 Bedford AV',
            city: 'Brooklyn',
            lat: 40.71685136553767,
            lon: -73.95871046589507,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'Williamsburg Thai Cuisine',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'wXj6q5yLLaiBBZde3O3yf5wAo56VX4TZEyqKK',
        transaction_id: 'n8DMXqw00yTEEdZkxDm9C8j5NK66Bqf8xqg83',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 13.23,
        category: [
            'Service',
            'Food and Beverage',
        ],
        category_id: '18021000',
        date: '2018-02-06',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'MA',
            store_number: null,
            zip: null,
        },
        name: '*SWEETGREEN7748',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'D1Q9ODo00zCXXPE3mrmnSjQDPy541Kfo1YP30',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 35,
        category: [
            'Healthcare',
            'Healthcare Services',
        ],
        category_id: '14001000',
        date: '2018-02-06',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'CITYMD - NY25',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'mJgOjmdvv3u55qjKLPLQT5RgD7b4bVTdOd8QK',
        transaction_id: 'JKOQyZXMMzFJJVADXvQXSO0X10kjr0sgLXEqn',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 55,
        category: [
            'Shops',
            'Clothing and Accessories',
            'Shoe Store',
        ],
        category_id: '19012003',
        date: '2018-02-06',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'CONVERSE # 60',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'PrZ63qoggzSgg7jyDvDbFpwvMO5gPkIMkwxNq',
        transaction_id: 'xn9LmZKDDxi33yP8KO4KU60wY0OAV0CL6JBy4',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 9.09,
        category: [
            'Food and Drink',
            'Restaurants',
        ],
        category_id: '13005000',
        date: '2018-02-06',
        location: {
            address: '62  Prince St',
            city: 'New York',
            lat: 40.723644,
            lon: -73.996803,
            state: 'NY',
            store_number: null,
            zip: '10012',
        },
        name: 'Soho Park',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: '1Yzy7xErrpfRRZwNvJvjFDxA9QBq0KI1Kbv77',
        transaction_id: '8Y1rJzVLLpfVVMbxEznEI4m6EmQLZmU56JjBe',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 45.13,
        category: [
            'Shops',
            'Supermarkets and Groceries',
        ],
        category_id: '19047000',
        date: '2018-02-06',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Whole Foods',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'D1Q9ODo00zCXXPE3mrmnS49jVdr7ZNFo1YaLb',
        transaction_id: 'a3baDQ566zfkkLgVzxyzU0xKJx4kZxHPD9rbN',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 0.51,
        category: [
            'Shops',
        ],
        category_id: '19000000',
        date: '2018-02-04',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'WA',
            store_number: null,
            zip: null,
        },
        name: 'Amazon',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'EPJV0Qojjzi445JMzVzecaZkANqMp8UwYwO1P',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 9.75,
        category: [
            'Food and Drink',
            'Restaurants',
        ],
        category_id: '13005000',
        date: '2018-02-04',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'DOS TOROS- WILLIAMSBUR',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'Ra4Db3oggzCooEJVwdwOTXDXdorw5wC8zpeDZ',
        transaction_id: '1Yzy7xErrpfRRZwNvJvjFA5PdNaDMEf1Kbw84',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 11.88,
        category: [
            'Shops',
        ],
        category_id: '19000000',
        date: '2018-02-03',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'WA',
            store_number: null,
            zip: null,
        },
        name: 'Amazon',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'MvAXPjEggziRR7bNKEKXT8j1qgYKnXHQ1QvmD',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 1.49,
        category: [
            'Shops',
            'Supermarkets and Groceries',
        ],
        category_id: '19047000',
        date: '2018-02-03',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'CITY ACRES MARKET BROOKLYN XXXX-XXXX-XXXX-9024',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'wXj6q5yLLaiBBZde3O3PhZBYykbr99IZ1xxwo',
        transaction_id: 'oZ1Ena6jjKSMMwqAPBPdcENrAz9gxLsaxaR91',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 19.59,
        category: null,
        category_id: null,
        date: '2018-02-03',
        location: {
            address: null,
            city: 'Brooklyn',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'PINK PUSSYCAT BOUTIQUE',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'LAmpbnoMMzHjjVkPQ5Qkf4Bpaa4zndIYwgpoD',
        transaction_id: 'Q4QLBroggzupp7kKXaXQUoD0x8VPBmTknkAZo',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 7.5,
        category: [
            'Shops',
            'Food and Beverage Store',
        ],
        category_id: '19025000',
        date: '2018-02-03',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'SQU*SQ *LA COLOMBE - N',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: '1Yzy7xErrpfRRZwNvJvgte94mkdBnnf1KOxOE',
        transaction_id: '5YEvJgzddpfxxez8MyM3Sxvze0Qa9XULXLr0M',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 26.13,
        category: [
            'Shops',
            'Beauty Products',
        ],
        category_id: '19006000',
        date: '2018-02-03',
        location: {
            address: '27 9th Ave',
            city: 'New York',
            lat: 40.7343,
            lon: -74.006,
            state: 'NY',
            store_number: '398',
            zip: '10014',
        },
        name: 'Sephora',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'D1Q9ODo00zCXXPE3mrmoieVwA8Prqqfo1yKyg',
        transaction_id: 'JKOQyZXMMzFJJVADXvXEfBy5KODpXLUgOgKMB',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 35.09,
        category: [
            'Shops',
            'Clothing and Accessories',
        ],
        category_id: '19012000',
        date: '2018-02-03',
        location: {
            address: '98 6th St',
            city: 'Brooklyn',
            lat: 40.718426,
            lon: -73.960442,
            state: 'NY',
            store_number: '1014',
            zip: '11249',
        },
        name: 'Urban Outfitters',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'D1Q9ODo00zCXXPE3mrmEt1Rwnn1qkNho1b8Yd',
        transaction_id: '8Y1rJzVLLpfVVMbxEzEPu7zbr43a6wu5L5oXX',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 12,
        category: [
            'Food and Drink',
            'Restaurants',
        ],
        category_id: '13005000',
        date: '2018-02-02',
        location: {
            address: '24  8th Ave',
            city: 'New York',
            lat: 40.737732,
            lon: -74.004341,
            state: 'NY',
            store_number: null,
            zip: '10014',
        },
        name: 'Kawa Sushi',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'oZ1Ena6jjKSMMwqAPBPqu1P7EqVv5gtajmOar',
        transaction_id: 'Z6vkyr5ggzh11a5xngn7SNJ6depgB0tQAQeKY',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 49.98,
        category: [
            'Shops',
        ],
        category_id: '19000000',
        date: '2018-02-01',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'WA',
            store_number: null,
            zip: null,
        },
        name: 'Amazon',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'yn7DRVk11JiyyK8ZQdQ8iLrowQg1mwFLzOyQg',
        transaction_type: 'place',
    },
    {
        account_id: '0YE3QNejjpfDDEOx3d5Ef14gVpPBJvcJwYyNX',
        account_owner: null,
        amount: 10.5,
        category: [
            'Food and Drink',
            'Restaurants',
            'Fast Food',
        ],
        category_id: '13005032',
        date: '2018-02-01',
        location: {
            address: '2271  Broadway',
            city: 'New York',
            lat: 40.785571,
            lon: -73.978904,
            state: 'NY',
            store_number: '33536',
            zip: '10024',
        },
        name: "McDonald's",
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: 'Q4QLBroggzupp7kKXaXjtOpExmQjk8Hkndnxk',
        transaction_id: 'Ra4Db3oggzCooEJVwdw6SxbnJPVZEkU8z8XvQ',
        transaction_type: 'place',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 4.01,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-24',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '2217',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'M483mPZgYMUyAB16yXKZFw7w7eEB9AsQJYqR3',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 5.21,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-24',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: true,
        pending_transaction_id: null,
        transaction_id: 'ZEp81yJgVqCwRv6ew7nXfXQ1ky9pAAFQndj6p',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 112,
        category: [
            'Transfer',
            'Billpay',
        ],
        category_id: '21003000',
        date: '2018-02-23',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'BANK OF AMERICA CREDIT CARD Bill Payment',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'Kj8qZQvgXVHpKL4dpBaxUE8XOoO5mVUZPbq81',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 60,
        category: [
            'Transfer',
            'Withdrawal',
            'ATM',
        ],
        category_id: '21012002',
        date: '2018-02-23',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'BKOFAMERICA ATM 02/23 #000004737 WITHDRWL EAST VILLAGE',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'kE618gxke5C4X6o94eaAtO6gw1wqReH48YyJp',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: -112,
        category: [
            'Payment',
            'Credit Card',
        ],
        category_id: '16001000',
        date: '2018-02-23',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'PAYMENT - THANK YOU',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '0143',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'APrOAK3kZxIxRm9kxMj8sJYLwVwpnNfkLyPeB',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: -3188.52,
        category: null,
        category_id: null,
        date: '2018-02-15',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'ZOCDOC INC DES:DIRECT DEP ID:XXXXX18257865TJ INDN:GRANDERSON,TREY CO ID:XXXXX11103 PPD',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '78qJLRm6AyFyErBPyoQ6UoXMrOAr7YhOK3XrK',
        transaction_type: 'unresolved',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 40,
        category: [
            'Transfer',
            'Withdrawal',
            'ATM',
        ],
        category_id: '21012002',
        date: '2018-02-14',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'BKOFAMERICA ATM 02/14 #000002168 WITHDRWL ONE PENN PLAZA',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '1jw0V74rqDHDnKjMD8Q3syXAoyXJBns1kZZ7K',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 9.99,
        category: [
            'Service',
            'Subscription',
        ],
        category_id: '18061000',
        date: '2018-02-14',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'Spotify',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '3932',
        },
        pending: false,
        pending_transaction_id: 'Lr8B5bEMVOfp1EawpRo4UmbzO03xnPuYMELVR',
        transaction_id: 'PJmk73jgVQtA3nbQApeVhaAvmaA35XUMz66Ne',
        transaction_type: 'place',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 6.44,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-13',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '9641',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'XEQxLrjgO1CJjk5RJ4w3TgBexPxEjai7VaLBY',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 1.99,
        category: [
            'Shops',
            'Digital Purchase',
        ],
        category_id: '19019000',
        date: '2018-02-12',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Google Cloud Storage',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Google Wallet',
            ppd_id: null,
            reason: null,
            reference_number: '8031',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'oYP3bnLje7FEj604ELVKCgjb1Kj4ZLTazyg3b',
        transaction_type: 'digital',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 9.99,
        category: [
            'Service',
            'Business and Strategy Consulting',
        ],
        category_id: '18007000',
        date: '2018-02-12',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'ONLYFANS.COM STRIPE.COM',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '6050',
        },
        pending: false,
        pending_transaction_id: 'pMqygmDre9hMr6mqMxNjckb7v6qjjYsOdQa1X',
        transaction_id: 'bQZVAo9Le0TOJjAQOPkeI1X3R4X9mPtAQoR8g',
        transaction_type: 'place',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 1775,
        category: [
            'Transfer',
            'Withdrawal',
            'Check',
        ],
        category_id: '21012001',
        date: '2018-02-08',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Check 76',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '00000000076',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'bQZVAo9Le0TOJjAQOPkjsrYeav88Z7UAQx6EX',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 12.99,
        category: [
            'Service',
            'Business and Strategy Consulting',
        ],
        category_id: '18007000',
        date: '2018-02-08',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'ONLYFANS.COM STRIPE.COM',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '8792',
        },
        pending: false,
        pending_transaction_id: 'pMqygmDre9hMr6mqMxNMH0AzNNkvrXtOVe0AN',
        transaction_id: 'gEZw4kzBexCvB8xjvkw8SdbnMQLLr1IZpMXev',
        transaction_type: 'place',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 15,
        category: [
            'Service',
            'Business and Strategy Consulting',
        ],
        category_id: '18007000',
        date: '2018-02-08',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'NV',
            store_number: null,
            zip: null,
        },
        name: 'ONLYFANS.COM STRIPE.COM',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '9501',
        },
        pending: false,
        pending_transaction_id: 'XEQxLrjgO1CJjk5RJ4wJs4NDKKQErYC7prBzx',
        transaction_id: '78qJLRm6AyFyErBPyoQrhmPgJNXXwRCO943VO',
        transaction_type: 'place',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 24,
        category: [
            'Transfer',
            'Third Party',
            'Venmo',
        ],
        category_id: '21010001',
        date: '2018-02-08',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Venmo',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'oYP3bnLje7FEj604ELV6SEDyqoOOPesazdJmR',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 40,
        category: [
            'Transfer',
            'Withdrawal',
            'ATM',
        ],
        category_id: '21012002',
        date: '2018-02-07',
        location: {
            address: null,
            city: 'New York',
            lat: null,
            lon: null,
            state: 'NY',
            store_number: null,
            zip: null,
        },
        name: 'BKOFAMERICA ATM 02/07 #000009243 WITHDRWL SOHO',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'xM046mkDephMmqkaMbnEC6Z79DkqK0UL6Arbq',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 1983,
        category: [
            'Transfer',
            'Debit',
        ],
        category_id: '21006000',
        date: '2018-02-07',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Online Banking payment to CRD 1714 Confirmation# 1701735231',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'J0YP8yrMV9tqax5bqBY6tOBaP3xn80tgLAo4z',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: -1983,
        category: [
            'Payment',
            'Credit Card',
        ],
        category_id: '16001000',
        date: '2018-02-07',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Online payment from CHK 7',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '2313',
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'ZEp81yJgVqCwRv6ewY4LfeNxobPaVMIQZzJgZ',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: -1982.93,
        category: [
            'Tax',
            'Refund',
        ],
        category_id: '20001000',
        date: '2018-02-07',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'TAX PRODUCTS PE3 DES:SBTPG LLC ID:XXXXX2282 INDN:GRANDERSON TREY CO ID:XXXXX60102 PPD',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '8ZB8DJdLvKIXy4DpXKZYT47AkdvVOmf56mQEw',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 4.09,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-06',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '6794',
        },
        pending: false,
        pending_transaction_id: '5m1awJrdKBfBL0AEBp4LUDNq0ojrnZILX7538',
        transaction_id: '34LrM0Ra3PUPjA3zPMbPu6egaOQ0vbFe8D1RD',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 10,
        category: [
            'Transfer',
            'Third Party',
            'Venmo',
        ],
        category_id: '21010001',
        date: '2018-02-06',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Venmo',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'Bq4Mv3yA5JcJ8L69JYQJsy0v6ZB3pXhxo4Brx',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 4.41,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-05',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '5377',
        },
        pending: false,
        pending_transaction_id: 'D38djOk0bZuwkOnqw4vphebpxveLpJCo1yXJD',
        transaction_id: 'ep9EjyxPe4FkPx56kgQBsOVjvVQneMfjVj8BD',
        transaction_type: 'special',
    },
    {
        account_id: '34LrM0Ra3PUPjA3zPM9NFYJPnZ5LdZcLwEMJ7',
        account_owner: null,
        amount: 4.57,
        category: [
            'Travel',
            'Car Service',
            'Ride Share',
        ],
        category_id: '22006001',
        date: '2018-02-05',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: 'CA',
            store_number: null,
            zip: null,
        },
        name: 'Lyft',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: '5541',
        },
        pending: false,
        pending_transaction_id: 'Eynwr0Njg5C6dYkE6aZwc6X19Eqwg8FwYewgk',
        transaction_id: 'YEZJDMjgVmCOX3LrOdb0TokOVkgJrMurVrKvV',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 485.29,
        category: [
            'Service',
            'Financial',
            'Loans and Mortgages',
        ],
        category_id: '18020004',
        date: '2018-02-01',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Earnest Loan CO DES:Payables ID:670489 INDN:Trey Granderson CO ID:XXXXX63747 WEB PMT INFO:Earnest Contact Phone # 1.866.764.9262',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '953Z1JwD0khk9aZnk40NfYVmaL7E3NfaN40e7',
        transaction_type: 'place',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 30,
        category: [
            'Transfer',
            'Third Party',
            'Venmo',
        ],
        category_id: '21010001',
        date: '2018-02-01',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Venmo',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: '78qJLRm6AyFyErBPyoQ1fyg9pa4QkdUOKE1V9',
        transaction_type: 'special',
    },
    {
        account_id: 'qMBm7o14eVhM4dZYMxN9HjN84DZg0DHn8g5o1',
        account_owner: null,
        amount: 800,
        category: [
            'Transfer',
            'Third Party',
            'Venmo',
        ],
        category_id: '21010001',
        date: '2018-02-01',
        location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
        },
        name: 'Venmo',
        payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: 'Braintree',
            ppd_id: null,
            reason: null,
            reference_number: null,
        },
        pending: false,
        pending_transaction_id: null,
        transaction_id: 'VEo4wMOgVLCa95gnaVPrC0pYPXK7mMUQ0Y91N',
        transaction_type: 'special',
    },
];
